### ISSUE TITLE
neoconf.nvim is ignoring `root_dir`

### ISSUE THREAD

**Issue by datwaft** [folke/neoconf.nvim#1]
This issue is a continuation of https://github.com/neovim/nvim-lspconfig/issues/2273.

Yesterday I had an issue in which my custom `root_dir` configuration was being ignored. I found that it is caused by `neoconf.nvim`.

Here is the minimal configuration with which it can be reproduced:

```lua
require("neoconf").setup({})

local lspconfig = require("lspconfig")

lspconfig.denols.setup({
  root_dir = lspconfig.util.root_pattern("deno.json", "deno.jsonc"),
})

lspconfig.tsserver.setup({
  root_dir = lspconfig.util.root_pattern("package.json"),
})
```

You need to have either a deno or a tsserver project with a `.vscode/settings.json` file.

As you can see in the following screenshot, both language servers are being loaded. If I remove the `.vscode/settings.json` file it works as expected.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/205132937-7d575ab0-1824-4710-baa6-45d55d4b0333.png">

**Comment by folke** [comment]
I dont have a solution yet, since this is more a feature than a bug.

Neoconf adds the relevant json config file patterns to the main `root_dir` for lspconfig on purpose.

An LSP will attach if either the original root_dir matches, or if the directory contains one of the markers like a `.vscode` folder in your case.

This is wanted behavior for most users, since that directory does in fact denote the root_dir.

Your issue is that your are (abusing?) the lspconfig root_dir mechanism to disable a certain LSP server for certain directories.

Because again, regardless of what LSP starts, that directory **IS** the root directory.

There's no easy fix, but I'll sde if I can add something where you can explicitely disable/enable some LSP server in your project settings. Probably the cleanest way t fix this.

**Comment by theoribeiro** [comment]
@folke Another use case is a monorepo with lots of .vscode folders inside each project. 
In our case, we have a yarn workspace and I want tsserver's Root Dir to be the root dir of the repo, not a subdir where I have a .vscode/settings.json file. Otherwise, tsserver will not be able to find our local yarn packages in the same monorepo. 

A suggestion is to add a `plugins.lspconfig.override_root_dir` setting, what do you think?

**Comment by redxtech** [comment]
I will say I am glad I found a source for this issue, I thought I was going crazy last night with trying to figure out how to disable `tsserver` for deno files. I tried what worked for my old config, but that did nothing.

Hopefully you're able to work on this soon, it would be really nice to be able to manually disable tsserver in deno projects rather than doing something hacky like the `root_dir` change

**Comment by folke** [comment]
@redxtech that's a great idea! Just implemented that. In a typescript project, you can now do something like the below:

```json
{
  "lspconfig": {
    "denols": false,
    "tsserver": {
      "javascript.format.enable": false
    }
  }
}
```

**Comment by redxtech** [comment]
> @redxtech that's a great idea! Just implemented that. In a typescript project, you can now do something like the below:
> 
> ```json5
> {
>   "lspconfig": {
>     "denols": false, // disable denols
>     "tsserver": {
>       "javascript.format.enable": false
>     }
>   }
> }
> ```

Would this be handled with neoconf? If not, where would I put that config?

I haven't used neoconf before, so I'm not familiar with it, but I will definitely be reading up on it now!

**Comment by redxtech** [comment]
Oh, that's nice and easy!

Thanks for the speedy replies (and useful projects as well)!

**Comment by redxtech** [comment]
One more question: would there be any way to automatically apply this setting to any project folder with a `deno.json` file in the root directory? Such as global config in `~/.config/nvim/neoconf.json`, but subsets that only apply if certain conditions are met? Maybe it would be more complicated like a lua function or something?

```json
{
  "lspconfig": {
    "denols": {},
    "tsserver": false
  }
}
```

**Comment by redxtech** [comment]
Is there any way to automatically apply this (or any predefined config) based on folder contents? Or would that be something that could be added? I'd be open to looking into potentially opening a PR if you would be open and don't think it would be too much of a mess to implement.
