### ISSUE TITLE
Feature: make neovim options configurable.

### ISSUE THREAD

**Issue by leaxoy** [folke/neoconf.nvim#2]
As title describe.

**Comment by jalcine** [comment]
Saw this the other day and was able to hack together this plugin, [https://git.jacky.wtf/neovim/neoconf-neovim-configuration](https://git.jacky.wtf/neovim/neoconf-neovim-configuration). Let me know if it works as expected. I use it myself now because I wanted to define providers on a per-machine basis.

(Originally published at: https://jacky.wtf/2023/1/bDw4)
